# Generated by Django 5.1.15 on 2026-05-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('court', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('violation_type', models.CharField(choices=[('air_pollution', 'Air Pollution'), ('water_pollution', 'Water Pollution'), ('noise_pollution', 'Noise Pollution'), ('solid_waste', 'Solid Waste'), ('hazardous_waste', 'Hazardous Waste'), ('deforestation', 'Deforestation'), ('wildlife', 'Wildlife / Biodiversity'), ('climate_change', 'Climate Change'), ('eia_violation', 'EIA / IEE Violation'), ('neqs_violation', 'NEQS Violation'), ('multi_media', 'Multi-Media Pollution'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('summary', models.TextField(blank=True, default='')),
                ('full_text', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', help_text="Comma-separated tags (e.g. 'NEQS, effluent, fine').", max_length=500)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-year', 'case_title'],
                'indexes': [models.Index(fields=['year'], name='cases_case_year_07e233_idx'), models.Index(fields=['violation_type'], name='cases_case_violati_c03db5_idx'), models.Index(fields=['country'], name='cases_case_country_630f33_idx')],
            },
        ),
    ]
